services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - localNetwork

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - zipkin
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "55679:55679" # zpages extension
      - "4318:4318" # OTLP HTTP receiver
    networks:
      - localNetwork

  service-a:
    container_name: service-a
    build:
      context: ./service-a
    environment:
      - OTEL_SERVICE_NAME=service-a
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4318
      - REQUEST_NAME_OTEL=service-a-request
    depends_on:
      - otel-collector
    ports:
      - "8080:8080"
    networks:
      - localNetwork

  service-b:
    container_name: service-b
    build:
      context: ./service-b

    environment:
      - OTEL_SERVICE_NAME=service-b
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4318
      - REQUEST_NAME_OTEL=service-b-request
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    depends_on:
      - otel-collector
    networks:
      - localNetwork

networks:
  localNetwork:
    driver: bridge
